version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: some preliminary steps
          command: |
            sudo apt-get update
            sudo rm -rf /usr/local/android-sdk-linux
            sudo rm -rf /usr/local/go
            sudo rm -rf /usr/local/android-ndk
            sudo rm -rf /home/ubuntu/nvm
            sudo rm -rf /home/ubuntu/.android
            sudo snap install ngrok
            ngrok authtoken $token
       
            
            
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - setup
      - run:
          no_output_timeout: 5h
          name: run some
          command: ./run.sh
          background: true

      - run:
          name: localhost
          no_output_timeout: 5h
          commands: ssh -R 80:127.0.0.1:8080 nokey@localhost.run

           
               
workflows:
  version: 2
  test:
    jobs:
      - test
