version: 2.1
jobs:
  build:
    machine:
      - image: ubuntu-2004:202010-01
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: build recovery
          command: |
             mkdir -p tmp/recovery
             cd tmp/recovery
             git config --global color.ui false
             wget https://raw.githubusercontent.com/rokibhasansagar/slimhub_actions/main/cleanup.sh
             bash cleanup.sh
