version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: Update arm machine
          command: |
            sudo apt-get update
jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - setup
      - run:
          name: run some
          command: |
             mkdir -p tmp/recovery
             cd tmp/recovery
             git config --global color.ui false
             wget https://raw.githubusercontent.com/rokibhasansagar/slimhub_actions/main/cleanup.sh
             bash cleanup.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-medium
          
