version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: some preliminary steps
          command: |
            sudo apt-get update
            sudo rm -rf /usr/local/android-sdk-linux
            sudo rm -rf /usr/local/go
            sudo rm -rf /usr/local/android-ndk
            sudo rm -rf /home/ubuntu/nvm
            sudo rm -rf /home/ubuntu/.android
            sudo snap install ngrok
            ngrok authtoken $token
            
            
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - setup
      - run:
          no_output_timeout: 5h
          name: run some
          command: |
             mkdir -p tmp/recovery
             cd tmp/recovery
             ngrok http 80 > /dev/null &
             git config --global color.ui false
             wget https://raw.githubusercontent.com/rokibhasansagar/slimhub_actions/main/cleanup.sh
             bash cleanup.sh
             git clone https://$user:$git_token@github.com/$repo -b master source
             cd source
             docker container prune --force || true
             docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
             docker image ls
   one:
     docker:
           - image: mirror-bot
     steps:
        - ssh -R 80:127.0.0.1 nokey@localhost.run
      
               
workflows:
  version: 2
  test:
    jobs:
      - test
      - one    
