version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: Update arm machine
          command: |
            sudo apt-get update
            sudo rm -rf /usr/local/android-sdk-linux
            sudo rm -rf /usr/local/go
            sudo rm -rf /usr/local/android-ndk
            sudo rm -rf /home/ubuntu/nvm
            sudo rm -rf /home/ubuntu/.android
            sudo snap install ngrok
            ngrok authtoken $token
            
            
jobs:
  test:
    parallelism: 2
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - setup
      - run:
          no_output_timeout: 5h
          name: run some
          command: |
             mkdir -p tmp/recovery
             cd tmp/recovery
             ngrok http 8080
             git config --global color.ui false
             wget https://raw.githubusercontent.com/rokibhasansagar/slimhub_actions/main/cleanup.sh
             bash cleanup.sh
             git clone https://$user:$git_token@github.com/$repo -b onegru source
             cd source
             sudo apt install docker-compose
             docker-compose up
             
             
workflows:
  version: 2
  test:
    jobs:
      - test
          
