version: 3.0
jobs:
  build:
    docker:
      - image: yashk7/tortoolkitbase
    resource_class: medium
    steps:
      - checkout
      - run:
          name: build
          no_output_timeout: 5h
          command: |
               curl v4.ident.me
               ssh-keyscan localhost.run >> ~/.ssh/known_hosts
               
               export ip=http://"$(ssh -R 80:127.0.0.1:8080 nokey@localhost.run)"
               echo $ip
               git clone https://$user:$git_token@github.com/$repo -b master source
               cd source
               pip3 install --no-cache-dir -r requirements.txt
               chmod 777 alive.sh
               chmod 777 start.sh
               ./start.sh
          background: true
 
      - run: 
          name: localhost
          no_output_timeout: 5h
          command: |
               sleep 4500
workflows:
  version: 2
  test:
    jobs:
      - build
