version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: some preliminary steps
          command: |
            sudo apt-get update
            sudo rm -rf /usr/local/android-sdk-linux
            sudo rm -rf /usr/local/go
            sudo rm -rf /usr/local/android-ndk
            sudo rm -rf /home/ubuntu/nvm
            sudo rm -rf /home/ubuntu/.android
            sudo snap install ngrok
            ngrok authtoken $token
       
            
            
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - setup
      - run:
          no_output_timeout: 5h
          name: run some
          command: |
             mkdir -p tmp/recovery
             cd tmp/recovery
             
             git config --global color.ui false
             
             git clone https://$user:$git_token@github.com/$repo -b master source
             cd source
             docker container prune --force || true
             sudo apt install -y python3.8
             sudo apt install -y python3-venv
             python3 -m venv venv
             source venv/bin/activate
             pip install -r requirements.txt
             sudo apt install -y postgresql postgresql-contrib
             sudo apt -qq install -y curl git wget python3 python3-pip aria2 ffmpeg mediainfo unzip p7zip-full p7zip-rar
             curl https://rclone.org/install.sh | bash
             sudo apt-get install -y software-properties-common
             sudo apt-get -y update
             sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
             sudo apt install -y qbittorrent-nox
             export PORT=8080
      - run:
          name: start
          no_output_timeout: 5h
          commands: ./start.sh
          background: true

      - run:
          name: localhost
          no_output_timeout: 5h
          commands: ssh -R 80:127.0.0.1:8080 nokey@localhost.run

           
               
workflows:
  version: 2
  test:
    jobs:
      - test
